---
- name: "Conditional reboot Deian, RedHat, and FreeBSD"
  hosts: 

  vars:
    reboot_cmd_map:
      RedHat: "/usr/sbin/shutdown -r now"
      Debian: "/usr/sbin/reboot"
      FreeBSD: "/sbin/reboot"

  tasks:

    - name: "Set reboot command based on OS family"
      set_fact:
        reboot_cmd: "{{ reboot_cmd[ansible_os_family] | default('/sbin/reboot')}}"

    - name: "Conditionally reboot the system(s)"
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        reboot_command: "{{ reboot_cmd }}"
        test_command: "whoami"
        reboot_timeout: 600
        post_reboot_delay: 30
