---
- name: "Fetch multiple files from remote hosts"
  hosts: vps-linux
  vars:
    files_to_fetch:
      - /etc/fail2ban/jail.local
      - /etc/ssh/sshd_config
      - /etc/sudoers
      - /etc/motd
    dump_dir: "/content/Systems@Home/vps"
  
  tasks:
  - name: "Fetch the files"
    ansible.builtin.fetch:
      src: "{{ item }}"
      dest: "{{ dump_dir }}"
      flat: no
    loop: "{{ files_to_fetch }}"   
